### ISSUE TITLE
Error when trying to update the ServiceWorker

### ISSUE THREAD

**Issue by re2005** [antfu/vite-plugin-pwa#366]
### Describe the bug

I'm using this plugin and it does works nicely.

But my Sentry report is getting spammed with a lot of errors that comes as Unhandled.

Failed to update a ServiceWorker for scope ('https://app....') with script ('https://app.../sw.js'): An unknown error occurred when fetching the script.

<img width="1069" alt="Screenshot 2022-09-02 at 13 51 40" src="https://user-images.githubusercontent.com/2920357/188135934-8e2b48a6-b8ee-4228-b2be-ed43365204b4.png">

I can't manage to find the root cause. I've already set the base, scope urls but still the same.

```ts
export const pwaConfig: Partial<VitePWAOptions> = {
    registerType: 'prompt',
    minify: true,
    scope: '/',
    base: '/',
    manifest: {
        scope: '/',

```

This is my configuration:

```ts
<script lang="ts" setup>
    import { useRegisterSW } from 'virtual:pwa-register/vue';
    import { ref } from 'vue';

    const isLoading = ref(false);
    const intervalMS = 45 * 1000;
    const { offlineReady, needRefresh, updateServiceWorker } = useRegisterSW({
        onRegistered(r) {
            r &&
                setInterval(() => {
                    r.update();
                }, intervalMS);
        },
    });

    const handleUpdate = () => {
        isLoading.value = true;
        updateServiceWorker();
    };

    const close = async () => {
        offlineReady.value = false;
        needRefresh.value = false;
    };
</script>
```

Also noticed that when the website is being updates and the SW tried to reach the `sw.js` and it fails (404) it also generated a `exception` and that I can't handle properly on my app.

Any help is more than welcome since the amount of errors is pilling up and I may have to consider stop using the plugin or look into another solution.

Thanks!

### Reproduction

https://app.gelato.network

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 394.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Chrome Canary: 107.0.5275.0
    Firefox: 103.0.2
    Safari: 15.6.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@re2005 what can we do here if the update is failing? I have the app open and seems to be ok, the sw installed and there is no error on update (pinging sw.js each 45 seconds).

This plugin is not releated with the update call, the update call is provided by the browser, you will have the same problem using this plugin or another approach.

**Comment by userquin** [comment]
@re2005 still opened, update received and still with no errors...

![imagen](https://user-images.githubusercontent.com/6311119/188189280-6eecf6ac-5671-418c-9783-8b90a551256b.png)

**Comment by re2005** [comment]
@userquin Thanks for taking the time to check it!

The issue is that doesn't happen every time but it's happening quite often.
![Screenshot 2022-09-02 at 18 47 38](https://user-images.githubusercontent.com/2920357/188201083-26b45cbd-22fe-41b1-8fc6-3850bf75186d.png)

Another think that would be handy is to have the ability to handle the error when the sw.js tried to update the the .js/.css files  
 and they are not there. ie. deploying new code or when a container goes off for a few seconds and the request fails with 404.

**Comment by userquin** [comment]
@re2005 still opened without any error...

I don't know if it is posible to control the error, you can check if there is an error calling the update (maybe you need to add an event listener): change the interval callback to be async awaiting the result and add a try catch block:
- https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/update
- https://w3c.github.io/ServiceWorker/#service-worker-registration-update

**Comment by userquin** [comment]
@re2005 if the server can be down, maybe you need to do a ping to the sw.js prior to do the update call, if the ping fails, then don't do the call (increase the intervalMS it is too short, 30 min or 1 hour should be ok: if you need some critical info, just change the strategy for that api call using NetworkFirst instead StaleWhileRevalidate strategy):
```ts
const { offlineReady, needRefresh, updateServiceWorker } = useRegisterSW({
        onRegistered(r) {
            r &&
                setInterval(async () => {
                    try {
                       const response = await fetch('/sw.js', { cache: 'no-store', 'cache-control': 'no-cache' });
                       response && response.status === 200 && await r.update();
                    } catch (e) {
                      console.log('cannot ping/update sw.js', e);
                    }                    
                }, intervalMS);
        },
    });
```

**Comment by doutatsu** [comment]
That looks to be exactly the same issue as the one I am having - I'll try this solution out and curious to hear if @re2005 would have it fixed applying this solution

**Comment by userquin** [comment]
> That looks to be exactly the same issue as the one I am having - I'll try this solution out and curious to hear if @re2005 would have it fixed applying this solution

You can also check if the user is online, for example using https://vueuse.org/core/useonline/#demo

**Comment by re2005** [comment]
Thanks @userquin I'll give it a try to see if it will stop bleeding logs to Sentry. 🚀 

Will post some update soon. @doutatsu

**Comment by userquin** [comment]
> Thanks @userquin I'll give it a try to see if it will stop bleeding logs to Sentry. 🚀
> 
> Will post some update soon. @doutatsu

If my proposal works (it should) I'll add it to the docs in the corresponding section.

**Comment by re2005** [comment]
You may can also check using `window.navigator.onLine`

**Comment by userquin** [comment]
```ts
const { offlineReady, needRefresh, updateServiceWorker } = useRegisterSW({
        onRegistered(r) {
            r &&
                setInterval(async () => {
                    try {
                       const onLine = navigator && 'connection' in navigator ??  navigator.onLine : true
                       const response = onLine ? await fetch('/sw.js', { cache: 'no-store', 'cache-control': 'no-cache' }) : undefined;
                       response && response.status === 200 && await r.update();
                    } catch (e) {
                      console.log('cannot ping/update sw.js', e);
                    }                    
                }, intervalMS);
        },
    });

**Comment by userquin** [comment]
@re2005 @doutatsu another thing we should check is the state of the registration, we should also avoid to call update when the state is `installing`: 
- check point 4 here https://w3c.github.io/ServiceWorker/#service-worker-registration-update-
- https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/installing

```ts
      const { offlineReady, needRefresh, updateServiceWorker } = useRegisterSW({
        onRegistered(r) {
            r &&
                setInterval(async () => {
                    try {
                       const ping = !!r.installing && navigator && 'connection' in navigator ?  navigator.onLine : true
                       const response = ping 
                         ? await fetch('/sw.js', { 
                           cache: 'no-store', 
                           'cache-control': 'no-cache'
                         })
                         : undefined;
                       response && response.status === 200 && await r.update();
                    } catch (e) {
                      console.log('cannot ping/update sw.js', e);
                    }                    
                }, intervalMS);
        },
    });
```

**Comment by userquin** [comment]
I'll add an utility to allow do this stuff just providing the intervalMS as an option in the RegisteSWOptions

**Comment by re2005** [comment]
That's great @userquin thanks for the updates. I'll give it a try.

**Comment by re2005** [comment]
Tested the code you shared and the `catch` part is never reached. I'm not sure if the reason is because it's inside the callback `useRegisterSW` or the Interval.

**Comment by userquin** [comment]
@re2005 the problem is that calling the update without catching the error will throw the error, with the new code, if the server is down when pinging `sw.js`, the error will be never shown in the console since we're checking the status code and so the update will never be called.

ofc we can ping the `sw.js` and the server up, but calling update the server can be down, but now we catch the error (edge case), and so the error will only be shown in the client.

**Comment by userquin** [comment]
@doutatsu @re2005 is the problem solved with my code?

**Comment by re2005** [comment]
Hi @userquin. I see a a small improvement on the errors related to the `sw.js`  But still see some `unknown` errors.

I think we can  close this issue for now. Thank you very much for your time!

Cheers

**Comment by userquin** [comment]
@re2005 can you shared this small improvement? when I have time I'll try to add it as a new feature...

**Comment by userquin** [comment]
@re2005 @doutatsu the condition is wrong, the `installing` property should be null to send the update:
```ts
const { offlineReady, needRefresh, updateServiceWorker } = useRegisterSW({
        onRegistered(r) {
            r &&
                setInterval(async () => {
                    try {
                       const ping = !r.installing && navigator && 'connection' in navigator ?  navigator.onLine : true
                       const response = ping 
                         ? await fetch('/sw.js', { 
                           cache: 'no-store', 
                           'cache-control': 'no-cache'
                         })
                         : undefined;
                       response && response.status === 200 && await r.update();
                    } catch (e) {
                      console.log('cannot ping/update sw.js', e);
                    }                    
                }, intervalMS);
        },
    });
```

**Comment by re2005** [comment]
For me it reduced the amount of errors pretty much.

I'm doing something like this:

```ts

onRegistered(r) {
            r &&
                setInterval(async () => {
                    const resp = await axios.get('/sw.js', {
                        headers: {
                            'Cache-Control': 'no-cache',
                            Pragma: 'no-cache',
                            Expires: '0',
                        },
                    });
                    if (resp && resp?.status === 200) {
                        await r.update();
                    }
                }, intervalMS);

```

**Comment by userquin** [comment]
@re2005 using axios (use native `fetch`)? I stop using axios a few years ago (XHR is blocking), has been axios updated to use `fecth`?

**Comment by re2005** [comment]
`Axios` just for compatibility and some extra nice configurations.

**Comment by doutatsu** [comment]
My errors went down somewhat, but not entirely using this configuration:

```js
  const { needRefresh, updateServiceWorker } = useRegisterSW({
    immediate: true,
    onRegistered(r) {
      // eslint-disable-next-line no-unused-expressions
      r && setInterval(async () => {
        const resp = await fetch('/sw.js', {
          cache: 'no-store',
          'cache-control': 'no-cache',
        });

        if (resp?.status === 200) { await r.update(); }
      }, intervalMS);
    },
  });
```

I am still getting a couple of `Failed to update a ServiceWorker for scope` and a new `InvalidStateError: newestWorker is null` error. Going to try those extra conditions @userquin had in his code

**Comment by doutatsu** [comment]
> If newestWorker is null, return [a promise rejected with](https://webidl.spec.whatwg.org/#a-promise-rejected-with) an "[InvalidStateError](https://webidl.spec.whatwg.org/#invalidstateerror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException) and abort these steps.

Looks like newestWorker `null` is indeed an expected state that I need to handle

**Comment by doutatsu** [comment]
As I am writing up the code based on conditions you've wrote @userquin - I can see that `needRefresh` would return `true` even if `navigator.onLine` if `false` 🤔 But with your conditions, it means that you would see a prompt, but the update will never occur unless the person is back online.

I can of course add the condition to not show prompt when offline, but then does it make sense? Should `needRefresh` account for online status - or should that condition been removed from code you shared?

**Comment by userquin** [comment]
@doutatsu if the sw isn't updated, maybe there is bug in workbox-window, or a bug here: we should check `src/client/build/register.ts` module: the event should never be fired.

https://github.com/antfu/vite-plugin-pwa/blob/main/src/client/build/register.ts#L56

**Comment by userquin** [comment]
@doutatsu about the update, if the user is offline, how is it possible (receive the event)? There can be a race condition, received updated and then go offline, but it the user is offline you should deal with it (maybe we can provide some logic, but then we also need to remember that).

Edge case:
- user receives update: if offline between received and confirmed updated (remember and once online refresh page?)
- user clicks update: if offline, the same as before else reload page

My suggestion, show again the dialog, then refresh page (via update method): the user can lose data if we do it.

**Comment by doutatsu** [comment]
>  if the sw isn't updated, maybe there is bug in workbox-window

No no, what I meant is that because `onLine` is `false` we never reach `.update()` due to `ping` constant being `false` in your scenario. `const ping = !r.installing && navigator && 'connection' in navigator ?  navigator.onLine : true`

> about the update, if the user is offline, how is it possible (receive the event)

No, you are totally right. I was using the built-in offline capability 
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4270980/190674100-a8a04f05-4432-4b94-8bfe-66f5cc039bea.png">

Which I think confused me. While the app is `offline`, I am not actually online, so the browser seems to still pull the update. Which it wouldn't if I was _actually_ offline - I wonder if it's just a shortcoming on the browser side, for not allowing to pull new workers when `offline` is toggled

**Comment by userquin** [comment]
@doutatsu you're simulation tools, ok, don't worry, but then the call should be ok: the browser is offline. Test I made result also on your results, it seems dev tools is bypassing the offline check, I've found when testing offline, restarting the https-localhost and refreshing the page sometimes works (the sw is updated and the event fired).

**Comment by doutatsu** [comment]
Testing with disabling network _properly_, obviously it doesn't pull the new worker - so all is good in that instance. Coming back online, provides the prompt and update works as expected. I'll proceed with that then and see how it goes

**Comment by userquin** [comment]
the edge case is still present: if going offline while sw is updating...

**Comment by userquin** [comment]
@doutatsu  remember to also close your issue ;)

**Comment by doutatsu** [comment]
I think that edge-case should be rare enough for me not to worry about right now - but I'll observe the situation after this update. The code I've landed on is this, making more heavy use of guards compared to your original code:

```js
        if (!(!r.installing && navigator)) { return; }
        if (('connection' in navigator) && !navigator.onLine) { return; }

        const resp = await fetch('/sw.js', {
          cache: 'no-store',
          'cache-control': 'no-cache',
        });

        if (resp?.status === 200) { await r.update(); }
```

**Comment by userquin** [comment]
@doutatsu copy/paste from vueuse ;) !

Maybe you can send a PR to add this to the docs: if you can't, don't worry, I'll do it.

**Comment by userquin** [comment]
is this ok `if (!(!r.installing && navigator)) { return; }`?

**Comment by doutatsu** [comment]
> Maybe you can send a PR to add this to the docs: if you can't, don't worry, I'll do it.

Sure, I'll take a look, happy to contribute

**Comment by userquin** [comment]
@doutatsu https://github.com/antfu/vite-plugin-pwa/issues/374#issuecomment-1250103579 (instead using harcoded name, will work also in dev if devOptions enabled)

**Comment by userquin** [comment]
@doutatsu @re2005 I have included a new entry in the docs, you can check a preview here: https://deploy-preview-376--vite-plugin-pwa.netlify.app/guide/periodic-sw-updates.html#handling-edge-cases

**Comment by doutatsu** [comment]
It's still present by the looks of it, but it's a lot less common than before, as seen below. I might tweak it further, but this is good enough for me not to worry too much about

<img width="918" alt="image" src="https://user-images.githubusercontent.com/4270980/191814573-26dd57dc-5a8d-4317-a399-2e8bd572e547.png">

@userquin thanks for adding the extra docs - glad to see refactored code I wrote was useful 👍🏻

**Comment by doutatsu** [comment]
@re2005 How are things looking on your side... This error started to be more prevalent again 😫 

<img width="327" alt="image" src="https://user-images.githubusercontent.com/4270980/194701918-73770182-4867-49d7-ab85-4640342db4b9.png">

**Comment by re2005** [comment]
Hey @doutatsu on my side I see almost no errors, pretty much by first requesting the `sw.js` file before calling the update.

Good luck!

**Comment by doutatsu** [comment]
Thanks - quite bizarre indeed. It looks like most of the errors are about `newestWorker` being `null` now. Back to the drawing board I go 😫

**Comment by userquin** [comment]
@doutatsu add headers for request headers in the request init method, I use it with vue virtual module using head method (I ignore the error):
```ts
const {
  needRefresh,
  offlineReady,
  updateServiceWorker,
} = useRegisterSW({
  immediate: true,
  onRegisteredSW(swUrl, r) {
    r && setInterval(async () => {
      if (!(!r.installing && navigator))
        return

      if (('connection' in navigator) && !navigator.onLine)
        return

      try {
        const resp = await fetch(swUrl, {
          method: 'HEAD',
          headers: {
            'cache': 'no-store',
            'cache-control': 'no-cache',
          },
        })

        if (resp?.status === 200)
          await r.update()
      }
      catch (_) {
        // just ignore
      }
    }, 1800000) // <== 30 minutes
  },
})
```

**Comment by userquin** [comment]
with local server (not running and restarting with new content):

![imagen](https://user-images.githubusercontent.com/6311119/195049429-1249b80d-1958-4706-b444-d86c5c8021c6.png)

**Comment by userquin** [comment]
@doutatsu I'm using periodic sync for updates with latest version `^0.14.1` in Elk repo, you can try adding this logic:
https://github.com/elk-zone/elk/blob/main/plugins/pwa.client.ts#L44

I'm preparing Nuxt 3 integration, I'll try to add support in the plugin, maybe exposing a helper function

**Comment by Santas** [comment]
@doutatsu were you able to resolve this?

**Comment by doutatsu** [comment]
@Santas I ended up catching most errors, as per @userquin original suggestion, which eliminated this particular issue and other similar failed to fetch ones. I think majority of users are fine, but I am not 100% if ignoring these like this actually left some people not being able to update, but I think it should be fine
